# Template run for saving Katib images.

inputs:
  image:
    required: true
    type: string
  dockerfile:
    required: true
    type: string
  export-name:
    required: false
    type: string
  image-tag:
    required: false
    type: string
    default: "e2e-test"
  upload:
    required: false
    type: boolean
    default: true

runs:
  using: composite
  steps:
    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Make directory to save images
      shell: bash
      run: mkdir -p ${{ env.ARCHIVED_IMAGE_DIR }}

    - name: Build and Export
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        tags: ${{ inputs.image }}:${{ inputs.image-tag }}
        outputs: type=tar,dest=${{ env.ARCHIVED_IMAGE_DIR }}/${{ inputs.export-name }}.tar

    - name: Save Image
      if: ${{ inputs.upload }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.export-name }}
        path: ${{ env.ARCHIVED_IMAGE_DIR }}/${{ inputs.export-name }}.tar
