# Composite action to setup e2e tests.
name: Setup E2E Test
description: setup env for e2e test using the minikube cluster

inputs:
  kubernetes-version:
    required: true
    description: kubernetes version

runs:
  using: composite
  steps:
#    - name: Update
#      shell: bash
#      run: sudo apt-get update -y

    - name: Set Up Minikube Cluster
      uses: manusa/actions-setup-minikube@v2.7.2
      with:
        minikube version: 'v1.28.0'
        kubernetes version: ${{ inputs.kubernetes-version }}
        start args: --wait-timeout=60s
        driver: 'none'
        github token: ${{ env.GITHUB_TOKEN }}

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set Up Go env
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
