# Template for e2e tests.

inputs:
  cluster-name:
    required: false
    type: string
    default: katib-e2e-cluster
  experiments:
    required: true
    type: string
  kubernetes-version:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set Up KinD Cluster
      uses: helm/kind-action@v1.2.0
      with:
        version: v0.14.0
        node_image: kindest/node:${{ inputs.kubernetes-version }}
        cluster_name: ${{ inputs.cluster-name }}
        wait: 120s

    - name: Set Up Go env
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.10

    - name: Make directory to save images
      shell: bash
      run: mkdir -p ${{ env.ARCHIVED_IMAGE_DIR }}

    - name: Download Images
      uses: actions/download-artifact@v3
      with:
        path: ${{ env.ARCHIVED_IMAGE_DIR }}

    - name: Set Up KinD Cluster
      shell: bash
      run: ./test/e2e/v1beta1/scripts/gh-actions/setup-kind.sh ${{ inputs.cluster-name }} ${{ env.ARCHIVED_IMAGE_DIR }}

    - name: Set Up Katib
      shell: bash
      run: ./test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh

    - name: Run E2E Experiment
      shell: bash
      run: ./test/e2e/v1beta1/scripts/gh-actions/run-e2e-experiment.sh ${{ inputs.experiments }}
