# Reusable workflows for publishing Katib images.
name: Build And Publish Images

on:
  workflow_call:
    inputs:
      component-name:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

jobs:
  algorithm:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
#          github.repository == 'kubeflow/katib' &&
        if: >-
          github.repository == 'tenzen-y/katib' &&
          (github.ref == 'refs/heads/build-test' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release-') || startsWith(github.ref, 'refs/tags/v'))
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Component ${{ matrix.component-name }}
        #          github.repository == 'kubeflow/katib' &&
        if: >-
          github.repository == 'tenzen-y/katib' &&
          (github.ref == 'refs/heads/build-test' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release-') || startsWith(github.ref, 'refs/tags/v'))
        id: publish
        uses: ./.github/workflows/template-publish-image
        with:
          image: docker.io/kubeflowkatib/${{ inputs.component-name }}
          dockerfile: ${{ inputs.dockerfile }}
          push: true

      - name: Build Component ${{ matrix.component-name }}
        if: steps.publish.outcome == 'skipped'
        uses: ./.github/workflows/template-publish-image
        with:
          image: docker.io/kubeflowkatib/${{ inputs.component-name }}
          dockerfile: ${{ inputs.dockerfile }}
          push: false
