# Reusable workflows for publishing Katib images.
name: Build And Publish Images

on:
  workflow_call:
    inputs:
      component-name:
        required: true
        type: string
      platforms:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

jobs:
  build-and-publish:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        # Trigger workflow only for kubeflow/katib repository with specific branch (master, release-.*) or tag (v.*).
        if: >-
          github.repository == 'kubeflow/katib' &&
          (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release-') || startsWith(github.ref, 'refs/tags/v'))
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Component ${{ inputs.component-name }}
        # Trigger workflow only for kubeflow/katib repository with specific branch (master, release-.*) or tag (v.*).
        if: >-
          github.repository == 'kubeflow/katib' &&
          (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release-') || startsWith(github.ref, 'refs/tags/v'))
        id: publish
        uses: ./.github/workflows/template-publish-image
        with:
          image: docker.io/kubeflowkatib/${{ inputs.component-name }}
          dockerfile: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          push: true

      - name: Test Build For Component ${{ inputs.component-name }}
        if: steps.publish.outcome == 'skipped'
        uses: ./.github/workflows/template-publish-image
        with:
          image: docker.io/kubeflowkatib/${{ inputs.component-name }}
          dockerfile: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          push: false
