name: E2E Test with enas-cnn-cifar10

on:
  pull_request:
    paths-ignore:
      - "pkg/new-ui/v1beta1/frontend/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  e2e:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Test Env
        uses: ./.github/workflows/template-setup-e2e-test
        with:
          kubernetes-version: ${{ matrix.kubernetes-version }}

    strategy:
      fail-fast: false
      matrix:
        kubernetes-version: ["v1.23.0", "v1.23.1", "v1.23.2", "v1.23.3", "v1.23.4", "v1.23.5", "v1.23.6", "v1.23.7", "v1.23.8", "v1.23.9", "v1.24.0", "v1.24.1", "v1.24.2", "v1.24.3", "v1.24.4", "v1.24.5", "v1.24.6", "v1.24.7", "v1.24.8", "1.25.0", "1.25.1", "1.25.2"]
        # Comma Delimited
        experiments: ["enas-cpu"]
