name: Publish AutoML Algorithm Images

env:
  dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
  dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
on: push

jobs:
  # Suggestion Images.
  suggestion:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        suggestion-name:
          - "hyperopt"
          - "chocolate"
          - "hyperband"
          - "skopt"
          - "goptuna"
          - "optuna"
        basedir: ["suggestion"]
        include:
          - suggestion-name: "enas"
            basedir: "suggestion/nas"
          - suggestion-name: "darts"
            basedir: "suggestion/nas"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Suggestion ${{ matrix.suggestion-name }}
        uses: ./.github/workflows/template-publish-image
        with:
          image: docker.io/kubeflowkatib/suggestion-${{ matrix.suggestion-name }}
          dockerfile: cmd/${{ matrix.basedir }}/${{ matrix.suggestion-name }}/v1beta1/Dockerfile

#  # Early Stopping Images.
#  earlystopping-medianstop:
#    name: Early Stopping MedianStop
#    uses: kubeflow/katib/.github/workflows/template-publish-image.yaml@master
#    with:
#      image: docker.io/kubeflowkatib/earlystopping-medianstop
#      dockerfile: cmd/earlystopping/medianstop/v1beta1/Dockerfile
#    secrets:
#      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
#      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
