name: Publish Trial Images

on:
  push:
  pull_request:
    branches:
      - 'master'
      - 'release-.*'

jobs:
  trial:
    name: Publish Image
    uses: ./.github/workflows/build-and-publish-images.yaml
    with:
      component-name: ${{ matrix.trial-name }}
      dockerfile: ${{ matrix.dockerfile }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - trial-name: mxnet-mnist
            dockerfile: examples/v1beta1/trial-images/mxnet-mnist/Dockerfile
          - trial-name: pytorch-mnist-cpu
            dockerfile: examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.cpu
          - trial-name: pytorch-mnist-gpu
            dockerfile: examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.gpu
          - trial-name: tf-mnist-with-summaries
            dockerfile: examples/v1beta1/trial-images/tf-mnist-with-summaries/Dockerfile
          - trial-name: enas-cnn-cifar10-gpu
            dockerfile: examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.gpu
          - trial-name: enas-cnn-cifar10-cpu
            dockerfile: examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.cpu
          - trial-name: darts-cnn-cifar10-cpu
            dockerfile: examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.cpu
          - trial-name: darts-cnn-cifar10-gpu
            dockerfile: examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.gpu
          - trial-name: simple-pbt
            dockerfile: examples/v1beta1/trial-images/simple-pbt/Dockerfile
