name: Publish Trial Images

on:
  push:
  pull_request:
    paths-ignore:
      - "pkg/new-ui/v1beta1/frontend/**"

jobs:
  trial:
    name: Publish Image
    uses: ./.github/workflows/build-and-publish-images.yaml
    with:
      component-name: ${{ matrix.trial-name }}
      platforms: ${{ matrix.platforms }}
      dockerfile: ${{ matrix.dockerfile }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - trial-name: pytorch-mnist-gpu
            platforms: linux/amd64
            dockerfile: examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.gpu
